// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  joystickContainer: string;
  joystickHandle: string;
  leftJoystick: string;
  rendererContainer: string;
  rendererContainer3D: string;
  rightJoystick: string;
}
declare const cssExports: CssExports;
export default cssExports;
