// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  descriptions: string;
  list: string;
  sidebar: string;
}
declare const cssExports: CssExports;
export default cssExports;
